name: CI job

on: push
jobs:
    build_and_test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14,15,16]
        
      steps:
        - uses: actions/checkout@v2

        - name: setup node
          uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
        #this requires a package.json which is currently not there in the project 
          run: |
            npm install
            npm ci 
        # build and test scripts are also not written   
        - name: build
          run: |
            npm run build
            npm run test
    push_to_docker_hub:
    
      name: Push to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: northladder/northladder-assignment-node-server
